### ISSUE TITLE
Firefox: uBlock popup is blank

### ISSUE THREAD

**Issue by ozar** [uBlock-LLC/uBlock#1027]
Running Firefox 36.0.1 on Linux

The current data/stats areas and version indicator of the ublock popup are blank after upgrading from 0.9.1.1 to version 0.9.1.2-dev.1

I've tried simply upgrading, and I've tried removing uBlock, then fresh installing the dev version, but still no stats or version indicator on the popup.

Dropping back to 0.9.1.1 gets things working properly again.

**Comment by gorhill** [comment]
I've had the same symptom. Quitting and restarting Firefox solved the issue.

**Comment by ozar** [comment]
That's one thing I didn't try, so I'll give it another go and see what happens.  Thanks!

**Comment by ozar** [comment]
No luck here with a Firefox restart.  I noticed also that the dev version is leaving all filters off of the the 3rd-party filters tab.  Only the lines regarding auto-updates and parsing cosmetic filters is showing up, along with the custom filter examples.

**Comment by gorhill** [comment]
Can you look in the browser console<sup>[1]</sup> if there are error messages?

[1] <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-J

**Comment by gorhill** [comment]
What a strange coincidence... I just reproduced, my +_"3rd-party filters"_ pane is also empty.

Investigating.

**Comment by ozar** [comment]
With a fresh start in Firefox, opening the uBlock popup and checking the browser console is giving a security error:

SecurityError: The operation is insecure.     popup.js:36:0

**Comment by gorhill** [comment]
@Deathamns, @AlexVallat I am confused. The browser complains that `vAPI.lastError` is not a function, while it is clearly defined in `vapi-background.js`. I tried to launch the browser to break on `vAPI.lastError()` in `assets.js`, but the breakpoint was never triggered:

![d](https://cloud.githubusercontent.com/assets/585534/6659155/fe043242-cb54-11e4-86f1-598ad6b678b3.png)

**Comment by gorhill** [comment]
@ozar I don't get this one. What operation, are there details about it?

**Comment by ozar** [comment]
No details really.  The console had many lines, I cleared it, then opened the uBlock popup, and that one line regarding security is all that comes up unless I do other things in Firefox.  Of course, the data is still missing from the popup window.

**Comment by gorhill** [comment]
My popup works, it's my 3rd-party filters pane which is broken.

There seems to be something going on, I can't tell what. I get these "security error" warnings too:

```
Security Error: Content at moz-nullprincipal:{41ee2473-2e49-46e9-b9f2-dcd73dcdc6d9} may not load or link to chrome://ublock/content/settings.html.
Security Error: Content at moz-nullprincipal:{41ee2473-2e49-46e9-b9f2-dcd73dcdc6d9} may not load or link to chrome://ublock/content/3p-filters.html.
```

I can't tell what is `{41ee2473-2e49-46e9-b9f2-dcd73dcdc6d9}`. This remiinds me of this other report earlier today: https://github.com/gorhill/uBlock/issues/1020#issuecomment-81196747. However as opposed to that case, I have no other add-on enabled.

**Comment by gorhill** [comment]
Quitting and restarting Firefox fixed the issue on my side, but there is definitely a problem to fix somewhere.

**Comment by ozar** [comment]
I generally only use static filtering, but just noticed that even when I try to use dynamic filtering, the popup won't open up fully giving me access to the advanced information.  It remains in static mode, with no stats.  Restarting Firefox doesn't help in my case.

**Comment by my-password-is-password** [comment]
@gorhill is `{41ee2473-2e49-46e9-b9f2-dcd73dcdc6d9}` some generated id for ublock?  Because that id I had in my error from that screenshot is now another id :

```
Security Error: Content at moz-nullprincipal:{2dce829b-50fb-4042-b19d-3197ea600260} may not load or link to chrome://ublock/content/3p-filters.html.
```

**Comment by gorhill** [comment]
I have a feeling this might be related to [that change](https://github.com/gorhill/uBlock/commit/f6ccacf550e6b39b9dc1fa8a5cb4ddd58647479f#diff-b3d0e3c6d1dfa1328422a2c493663d9a), because the first thing executed when opening the popup is accessing that local storage. That storage is also used in the 3rd-party filters pane.

Anyways, I will remove the use from the popup, as in the end it did not solve the issue I was trying to solve( #996).

**Comment by gorhill** [comment]
@my-password-is-password Yes, after restarting Firefox I get similar errors but with a new id.

**Comment by ozar** [comment]
Note that all the issues I've described above, including the security issue in console, go away when I drop back to version 0.9.1.1

**Comment by gorhill** [comment]
Yes, 0.9.1.1 is almost same as 0.9.1.0, it was mostly an emergency fix for Chromium. 0.9.1.1 does not contains that local storage code.

**Comment by Deathamns** [comment]
I changed `vAPI.localStorage` to Firefox config (which shouldn't be used for large data), test with that...

By the way, about these `Security Error: Content at moz-nullprincipal...` errors, just ignore them.

**Comment by ozar** [comment]
Just a quick not to say that version 0.9.1.2-dev.2 has fixed all the issues I've described above.

Thanks for the fixes.  :)

**Comment by ozar** [comment]
Just a quick note to say that version 0.9.1.2-dev.2 has fixed all the issues I've described above.

Thanks for the fixes. :)

EDIT:  sorry for the double post but for some reason, the GigHub software was not allowing me to edit the other post like this one.
